[[plugins]]
package = "@netlify/plugin-lighthouse"
  [plugins.inputs.settings]
  preset = "desktop"

[functions]
directory = "functions"

## Build settings

# Only run build on non-sanity branches
[build]
ignore = "node tontine/scripts/ignore_builds.js"

[context.deploy-preview]
base = "/tontine"
command = "npm run format-lint:fix && npm run build:tontine && npm run run-tests"
publish = ".next"

[context.staging]
base = "/tontine"
command = "npm run format-lint:fix && npm run build:tontine && npm run run-tests"
publish = ".next"

[context.production]
base = "/tontine"
command = "npm run format-lint && npm run build:tontine && npm run postbuild"
publish = ".next"

# Daily rebuild function
[context.production.functions."daily-rebuild"]
schedule = "30 12 * * *"
