## REDIRECTS

# Need these because netlify considers these as different paths
[[redirects]]
from = ":locale/FAQs"
to = ":locale/faqs/"
force = true

[[redirects]]
from = ":locale/FAQs/"
to = ":locale/faqs/"
force = true

## Build settings

# Only run build on non-sanity branches
[build]
ignore = "node ignore_builds.js"

[context.deploy-preview]
base = "."
command = "npm run format-lint:fix && npm run build:tontine && npm run tc-report:tontine && npm run run-tests"
publish = "tontine/.next"

[context.staging]
base = "."
command = "npm run format-lint:fix && npm run build:tontine && npm run tc-report:tontine && npm run run-tests"
publish = "tontine/.next"

[context.production-tontine]
base = "."
command = "npm run format-lint && npm run build:tontine && npm run postbuild"
publish = "tontine/.next"

### Scheduled functions

[functions]
directory = "netlify/functions"

[context.production-tontine.functions."daily-rebuild"]
schedule = "30 12 * * *"

[context.production-tontine.functions."test-scheduled-function"]
schedule = "@hourly"

## Plugins

[[context.production-tontine.plugins]]
package = "@sentry/netlify-build-plugin"
  [context.production-tontine.plugins.inputs]
  sentryOrg = "tontine"
  sentryProject = "javascript-nextjs"
  deployPreviews = false

[[plugins]]
package = "@netlify/plugin-lighthouse"
  [plugins.inputs.settings]
  preset = "desktop"